[package]
name = "kappa"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kappa-socks"
path = "src/kappa-socks.rs"

[[bin]]
name = "kappa-gateway"
path = "src/kappa-gateway.rs"

[dependencies]
async-stream = "0.3.6"
axum = "0.7.9"
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
bytes = "1.10.1"
clap = { version = "4.5", features = ["derive"] }
comprehensive = { version = "0.9.0" }
comprehensive_grpc = { version = "0.9.0", features = ["experimental", "tls"] }
comprehensive_http = { version = "0.4.0", features = ["tls"] }
comprehensive_spiffe = { version = "0.4.0" }
comprehensive_tls = { version = "0.5.0", features = ["dispatch"] }
disk = "0.1.21"
futures = "0.3.31"
html-escape = "0.2.13"
http = "1.3.1"
hyper-util = "0.1.17"
itertools = "0.14.0"
join-string = "0.3.0"
k8s-openapi = { version = "0.26.0", features = ["v1_30"] }
kube = { version = "2.0.1", features = ["aws-lc-rs"] }
log = "0.4.28"
mime = "0.3.17"
paste = "1.0.15"
pin-project-lite = "0.2.16"
prost = "0.14.1"
thiserror = "2.0.16"
tokio = { version = "1.40", features = ["rt-multi-thread", "macros"] }
tokio-rustls = "0.26.4"
tokio-util = "0.7.16"
tonic = "0.14.2"
tonic-prost = "0.14.2"
tonic-web = "0.14.2"
tower-http = { version = "0.6.6", features = ["cors"] }
tower-layer = "0.3.3"
tower-service = "0.3.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
x509-parser = "0.18.0"

[build-dependencies]
tonic-prost-build = "0.14.2"
