apiVersion: v1
kind: Namespace
metadata:
  name: kappa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kappa-gateway
  namespace: kappa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kappa-gateway-resolver
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kappa-gateway-resolver-binding
subjects:
- kind: ServiceAccount
  name: kappa-gateway
  namespace: kappa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kappa-gateway-resolver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kappa-gateway
  name: kappa-gateway
  namespace: kappa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kappa-gateway
  template:
    metadata:
      labels:
        app: kappa-gateway
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "2444"
        prometheus.io/scrape: "true"
        server-identity: "spiffe://vandry.org/ns/kappa/pod-label/app/kappa-gateway"
        server-diag-port: "1444"
    spec:
      serviceAccountName: kappa-gateway
      containers:
      - name: kappa-gateway
        image: vandry/kappa-gateway
        command:
        - "/kappa-gateway"
        - "--spiffe"
        - "--acl=spiffe://set.this.to/something/sensible"
        - "--grpcs-port=1443"
        - "--diag-https-port=1444"
        - "--grpc-port=2443"
        - "--diag-http-port=2444"
        livenessProbe:
          grpc:
            port: 2443
            service: ""
        readinessProbe:
          grpc:
            port: 2443
            service: "ready"
        volumeMounts:
          - name: spire-agent-socket
            mountPath: /run/spire/sockets
            readOnly: true
        ports:
        - containerPort: 1443
        ports:
        - containerPort: 1444
        ports:
        - containerPort: 2443
        ports:
        - containerPort: 2444
        env:
        - name: RUST_LOG
          value: info
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kappa-gateway
  namespace: kappa
spec:
  selector:
    app: kappa-gateway
  ports:
    - port: 1443
      targetPort: 1443
  type: ClusterIP
